server:
  port: 8080
  servlet:
    context-path: /api
spring:
  sql:
    init:
      mode: always
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5
    username: postgres
    password: Firoj@123
    url: jdbc:postgresql://localhost:5432/frj-saas
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
